sudo: false
language: rust
rust:
  - stable
  - nightly
  - beta

cache: 
  cargo: true
  directories:
    - "$HOME/kvoc"
    - "$HOME/.cargo"
    - "$HOME/.rustup"

notifications:
  email:
    on_success: never

env:
  global:
    - RUSTFLAGS="-C link-dead-code"
    - TRAVIS_CARGO_NIGHTLY_FEATURE=nightly

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev 

before_script: sh ci/before_script.sh
script: sh ci/script.sh
after_success: sh ci/after_success.sh
