[package]
name        = "ga"
version     = "0.1.1"
description = "Genetic algorithm traits and algorithm"
authors     = ["Will Johnston"]

license     = "MIT"
readme      = "README.md"
repository  = "https://github.com/wbjohnston/ga-rs.git"

[dependencies]
rand     = "0.3.16"
petgraph = "0.4"
ndarray  = "0.10.0"
rayon    = "0.8.2"
clippy   = { version = "*", optional = true }
