[package]
name        = "petri"
version     = "0.0.2"
description = "Evolutionary computing toolkit"
authors     = ["Will Johnston"]

license     = "MIT"
readme      = "README.md"
repository  = "https://github.com/wbjohnston/petri.git"

[features]
par     = ["rayon"]
gp      = []
ga      = []
default = ["ga"]

[dev-dependencies]
clap         = "2.26.2"

[dependencies]
rayon        = { version = "0.8.2", optional = true }
rand         = "0.3.16"
serde        = "1.0.15"
serde_derive = "1.0.15"
ndarray      = "0.10.0"
bit-vec      = "0.4.4"
