[package]
name        = "petri"
version     = "0.0.1"
description = "Genetic algorithm traits and algorithm"
authors     = ["Will Johnston"]

license     = "MIT"
readme      = "README.md"
repository  = "https://github.com/wbjohnston/petri.git"

[features]

par = ["rayon"]

gp = []

ga = []

default = ["ga"]

[dependencies]
rayon        = { version = "0.8.2", optional = true }
rand         = "0.3.16"
serde        = "1.0.15"
serde_derive = "1.0.15"
ndarray      = "0.10.0"
len-trait    = "0.6.0"
