[package]
name        = "petri"
version     = "0.1.4"
description = "Genetic algorithm traits and algorithm"
authors     = ["Will Johnston"]

license     = "MIT"
readme      = "README.md"
repository  = "https://github.com/wbjohnston/petri.git"

[features]

[dependencies]
rand         = "0.3.16"
serde        = "1.0.15"
serde_derive = "*"
ndarray      = "0.10.0"
len-trait    = "0.6.0"
