[package]
name        = "ge"
version     = "0.1.0"
description = "Genetic algorithm traits and algorithm"
authors     = ["Will Johnston"]

license     = "MIT"
readme      = "README.md"
repository  = "https://github.com/wbjohnston/ge-rs.git"

[dependencies]
rand = "0.3.16"
num = "0.1.40"
