[package]
name        = "ga"
version     = "0.1.4"
description = "Genetic algorithm traits and algorithm"
authors     = ["Will Johnston"]

license     = "MIT"
readme      = "README.md"
repository  = "https://github.com/wbjohnston/ga-rs.git"

[features]
lgp     = []
tgp     = ["petgraph"]
cgp     = ["petgraph"]

gp      = ["tgp"]
gp-par  = ["gp", "rayon"]

ga      = ["bit-vec"]
ga-par  = ["rayon"]

serde-g = ["serde"]

default = ["ga", "gp"]

[dependencies]
rand     = "0.3.16"
petgraph = { version = "0.4", optional = true }
bit-vec  = { version = "0.4.4", optional = true }
serde    = { version = "1.0.15", optional = true }
ndarray  = { version = "0.10.0", optional = true }
rayon    = { version = "0.8.2", optional = true }
